### ISSUE TITLE
Consider adding license to the project

### ISSUE THREAD

**Issue by CrsiX** [N0W0RK/TUM_GAD_Tests_SS21#15]
I think it would be good to specify a license for the project, especially if it's getting bigger and may be used by more people later. I would suggest some free & open-source license, but this has to be decided by @N0W0RK as creator, the current contributors and maybe the tutors or whoever is responsible for creating the exercises -- because the test cases are obviously related to the tasks.

**Comment by N0W0RK** [comment]
I would suggest GPL v3 but am open for suggestions.
