### ISSUE TITLE
More informative assert messages

### ISSUE THREAD

**Issue by N0W0RK** [N0W0RK/TUM_GAD_Tests_SS21#26]
I think it would be great, to give more output on the assert messages in [PivotFinderTester.java](https://github.com/N0W0RK/TUM_GAD_Tests_SS21/blob/main/GAD%206%20-%20Verbessertes%20Sortieren/tests/simplesort/PivotFinderTester.java) added with #24. Giving the user the array and search parameters directly, instead of them having too look this up manually would help a lot.

**Comment by babyygemperor** [comment]
Sure, would try to implement some

**Comment by N0W0RK** [comment]
There are still a lot of test cases that dont print too much usefull information, reopening this.
