### ISSUE TITLE
Add a CI pipeline to check for build errors and Java style guide violations

### ISSUE THREAD

**Issue by CrsiX** [N0W0RK/TUM_GAD_Tests_SS21#38]
Considering EiST with their exercise point reductions for bad code style... I would suggest to add a CI pipeline (e.g. Travis CI) to accomplish the following goals on our test suite(s):

- Prevent Java build errors
- Point out bad practices to avoid them later on
- Improve general coding style
- Encourage other students to adapt the idea of testing their own projects in this or similar way as well

After a quick search, there are some style guides around, e.g. [this](https://google.github.io/styleguide/javaguide.html) one from Google or [this](https://cr.openjdk.java.net/~alundblad/styleguide/index-v6.html) draft for OpenJDK (or [this](https://www.oracle.com/technetwork/java/codeconventions-150003.pdf) very old PDF document from Oracle?). From a quick point of overview, they seem to be quiet abstract but also consistent.

But that's not of particular interest now. The questions are: Do we need it at all? What tools should be used (if we agree on that)? I'm open for further discussion. :)

**Comment by JohannesStoehr** [comment]
You might want to use this as a baseline: https://github.com/ls1intum/Artemis/tree/develop/src/main/resources/templates/java/test/staticCodeAnalysisConfig
These are the style guides that Artemis uses, when evaluating your submissions

**Comment by CrsiX** [comment]
> You might want to use this as a baseline: https://github.com/ls1intum/Artemis/tree/develop/src/main/resources/templates/java/test/staticCodeAnalysisConfig

Thanks for the input. However, the pure config data isn't helpful on its own. What software uses this configuration? The bamboo server? This can't be used here I guess.

When nobody disagrees with the proposal, I would dive into [GitHub Actions](https://docs.github.com/en/actions/guides/about-continuous-integration) to accomplish this soon.

**Comment by JohannesStoehr** [comment]
This is used by Bamboo and run using Maven to run Spotbugs, PMD and Checkstyle. But at least some of them should also be available as GitHubActions afaik

**Comment by N0W0RK** [comment]
Just googled a bit and found [this](https://github.com/marketplace/actions/run-java-checkstyle) on GH Marketplace. Might be worth a look if you haven't found anything better.
